name: ci-checks
on: [push, pull_request]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get install -y ninja-build libgl1-mesa-dev libegl1-mesa-dev libglu1-mesa-dev lxde libxi-dev
          pip3 install meson

      - name: Build
        shell: bash
        run: |
          meson . build
          cd build
          ninja

      - name: Prepare upload
        shell: bash
        run: |
          mkdir -p upload/assets
          cp build/complementary upload/complementary
          cp -r build/assets/* upload/assets/*
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: complementary
          path: |
            upload/*

  build-mac:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        shell: bash
        run: |
          pip3 install meson

      - name: Build
        shell: bash
        run: |
          meson . build
          cd build
          ninja

      - name: Prepare upload
        shell: bash
        run: |
          mkdir -p upload/assets
          cp build/complementary upload/complementary
          cp -r build/assets/* upload/assets/*
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: complementary
          path: |
            upload/*

  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          sudo apt-get install clang-format
      - shell: bash
        run: |
          ! clang-format *.h *.cpp -style=file --output-replacements-xml | grep "<replacement "
